/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Reza22
 */
public class awal_pembimbing extends javax.swing.JFrame {

    /**
     * Creates new form awal_pembimbing
     */
    public awal_pembimbing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_searchPembimbing = new javax.swing.JButton();
        tb_searchPembimbing = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_Pembimbing = new javax.swing.JTable();
        b_InsertPembimbing = new javax.swing.JButton();
        b_deletePembimbing = new javax.swing.JButton();
        c_pilihLokasi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tb_namaPembimbing = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tb_nipPembimbing = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        D_Menu = new javax.swing.JMenu();
        D_Menu_Lokasi = new javax.swing.JMenuItem();
        D_Menu_Kelompok = new javax.swing.JMenuItem();
        D_Menu_Pembimbing = new javax.swing.JMenuItem();
        D_Menu_Mahasiswa = new javax.swing.JMenuItem();
        EXIT = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_searchPembimbing.setText("SEARCH");

        jLabel2.setText("SEARCH");

        t_Pembimbing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Pembimbing", "NIP", "Lokasi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t_Pembimbing);

        b_InsertPembimbing.setText("INSERT");

        b_deletePembimbing.setText("DELETE");

        jLabel1.setText("NAMA PEMBIMBING");

        jLabel3.setText("NIP PEMBIMBING");

        D_Menu.setText("MENU");

        D_Menu_Lokasi.setText("LOKASI");
        D_Menu.add(D_Menu_Lokasi);

        D_Menu_Kelompok.setText("KELOMPOK");
        D_Menu.add(D_Menu_Kelompok);

        D_Menu_Pembimbing.setText("PEMBIMBING");
        D_Menu.add(D_Menu_Pembimbing);

        D_Menu_Mahasiswa.setText("MAHASISWA");
        D_Menu.add(D_Menu_Mahasiswa);

        jMenuBar1.add(D_Menu);

        EXIT.setText("EXIT");
        jMenuBar1.add(EXIT);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tb_searchPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_searchPembimbing)
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c_pilihLokasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(b_InsertPembimbing)
                                .addGap(18, 18, 18)
                                .addComponent(b_deletePembimbing)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tb_nipPembimbing, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(tb_namaPembimbing))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_pilihLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tb_namaPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tb_nipPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_InsertPembimbing)
                    .addComponent(b_deletePembimbing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_searchPembimbing)
                    .addComponent(jLabel2)
                    .addComponent(tb_searchPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu D_Menu;
    private javax.swing.JMenuItem D_Menu_Kelompok;
    private javax.swing.JMenuItem D_Menu_Lokasi;
    private javax.swing.JMenuItem D_Menu_Mahasiswa;
    private javax.swing.JMenuItem D_Menu_Pembimbing;
    private javax.swing.JMenu EXIT;
    private javax.swing.JButton b_InsertPembimbing;
    private javax.swing.JButton b_deletePembimbing;
    private javax.swing.JButton b_searchPembimbing;
    private javax.swing.JComboBox<String> c_pilihLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_Pembimbing;
    private javax.swing.JTextField tb_namaPembimbing;
    private javax.swing.JTextField tb_nipPembimbing;
    private javax.swing.JTextField tb_searchPembimbing;
    // End of variables declaration//GEN-END:variables

    public int getPiliLokasi(){
        return c_pilihLokasi.getSelectedIndex();
    }
    
    public String getNamaPembimbing(){
        return tb_namaPembimbing.getText();
    }
    public String getNipPemimbing(){
        return tb_nipPembimbing.getText();
    }
    public String getSearchPembimbing(){
        return tb_searchPembimbing.getText();
    }
    public Object getB_Add(){
        return b_InsertPembimbing;
    }
    public void gagal(){
        JOptionPane.showMessageDialog(null, "Isi terlebih dahulu");
    }
    public void sukses(){
        JOptionPane.showMessageDialog(null, "Berhasil");
    }
    
    public Object getB_Delete(){
        return b_deletePembimbing;
    }
    public Object getD_Menu_Lokasi(){
        return D_Menu_Lokasi;
    }
    
    public Object getD_Menu_Kelompok(){
        return D_Menu_Kelompok;
    }
    
    public Object getD_Menu_Pembimbing(){
        return D_Menu_Pembimbing;
    }
    
    public Object getD_Menu_Mahasiswa(){
        return D_Menu_Mahasiswa;
    }
    public void reset(){
        tb_namaPembimbing.setText("");
        tb_nipPembimbing.setText("");
        tb_searchPembimbing.setText("");
    }
    
    public Object getB_search(){
        return b_searchPembimbing;
    }
    
    public Object getB_Exit(){
        return EXIT;
    }
    
     public JTable getTable(){
        return t_Pembimbing;
    }
     
     public JComboBox getComboBoxLokasi(){
        return c_pilihLokasi;
    }
    
    public void addListener(ActionListener e){
        b_InsertPembimbing.addActionListener(e);
        b_deletePembimbing.addActionListener(e);
        b_searchPembimbing.addActionListener(e);
        D_Menu_Lokasi.addActionListener(e);
        D_Menu_Kelompok.addActionListener(e);        
        D_Menu_Pembimbing.addActionListener(e);
        D_Menu_Mahasiswa.addActionListener(e);
        EXIT.addActionListener(e);
    }
    
    
}
