/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Aplikasi;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Reza22
 */
public class awal_kelompok extends javax.swing.JFrame {

    /**
     * Creates new form awal_kelompok
     */
    public awal_kelompok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_searchKelompok = new javax.swing.JButton();
        tb_searchKelompok = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_Kelompok = new javax.swing.JTable();
        b_InsertKelompok = new javax.swing.JButton();
        b_deleteKelompok = new javax.swing.JButton();
        c_pilihLokasi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tb_namaKelompok = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        D_Menu = new javax.swing.JMenu();
        D_Menu_Lokasi = new javax.swing.JMenuItem();
        D_Menu_Kelompok = new javax.swing.JMenuItem();
        D_Menu_Pembimbing = new javax.swing.JMenuItem();
        D_Menu_Mahasiswa = new javax.swing.JMenuItem();
        EXIT = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_searchKelompok.setText("SEARCH");

        jLabel2.setText("SEARCH");

        t_Kelompok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Kelompok", "Jumlah Anggota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t_Kelompok);

        b_InsertKelompok.setText("INSERT");

        b_deleteKelompok.setText("DELETE");

        jLabel1.setText("NAMA KELOMPOK");

        D_Menu.setText("MENU");

        D_Menu_Lokasi.setText("LOKASI");
        D_Menu.add(D_Menu_Lokasi);

        D_Menu_Kelompok.setText("KELOMPOK");
        D_Menu.add(D_Menu_Kelompok);

        D_Menu_Pembimbing.setText("PEMBIMBING");
        D_Menu.add(D_Menu_Pembimbing);

        D_Menu_Mahasiswa.setText("MAHASISWA");
        D_Menu.add(D_Menu_Mahasiswa);

        jMenuBar1.add(D_Menu);

        EXIT.setText("EXIT");
        jMenuBar1.add(EXIT);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tb_searchKelompok, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_searchKelompok)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c_pilihLokasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(b_InsertKelompok)
                                .addGap(18, 18, 18)
                                .addComponent(b_deleteKelompok)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tb_namaKelompok, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(c_pilihLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tb_namaKelompok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_InsertKelompok)
                    .addComponent(b_deleteKelompok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_searchKelompok)
                    .addComponent(jLabel2)
                    .addComponent(tb_searchKelompok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu D_Menu;
    private javax.swing.JMenuItem D_Menu_Kelompok;
    private javax.swing.JMenuItem D_Menu_Lokasi;
    private javax.swing.JMenuItem D_Menu_Mahasiswa;
    private javax.swing.JMenuItem D_Menu_Pembimbing;
    private javax.swing.JMenu EXIT;
    private javax.swing.JButton b_InsertKelompok;
    private javax.swing.JButton b_deleteKelompok;
    private javax.swing.JButton b_searchKelompok;
    private javax.swing.JComboBox<String> c_pilihLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_Kelompok;
    private javax.swing.JTextField tb_namaKelompok;
    private javax.swing.JTextField tb_searchKelompok;
    // End of variables declaration//GEN-END:variables

    
//    public void setPilihLokasi(){
//        Aplikasi temp = null;
//        String stemp;
//        c_pilihLokasi.removeAllItems();
//        if(c_pilihLokasi.getItemCount()== 0){
//            c_pilihLokasi.setName("Kosong");
//        }else{    
//            for (int i = 0; i < temp.getDaftarLokasi().size(); i++) {
//                stemp = temp.getDaftarLokasi().get(i).getNamaLokasi();
//            }
//        }
//     }
    
    public JComboBox getComboBox(){
        return c_pilihLokasi;
        
    }

    
    public int getPilihLokasi(){
        return c_pilihLokasi.getSelectedIndex();
    }
    
    public String getNamaKelompok(){
        return tb_namaKelompok.getText();
    }
    public String getSearchKelompok(){
        return tb_searchKelompok.getText();
    }
    public Object getB_Add(){
        return b_InsertKelompok;
    }
    public void gagal(){
        JOptionPane.showMessageDialog(null, "Isi terlebih dahulu");
    }
    public void sukses(){
        JOptionPane.showMessageDialog(null, "Berhasil");
    }
    public Object getB_Delete(){
        return b_deleteKelompok;
    }
    public Object getD_Menu_Lokasi(){
        return D_Menu_Lokasi;
    }
    
    public Object getD_Menu_Kelompok(){
        return D_Menu_Kelompok;
    }
    
    public Object getD_Menu_Pembimbing(){
        return D_Menu_Pembimbing;
    }
    
    public Object getD_Menu_Mahasiswa(){
        return D_Menu_Mahasiswa;
    }       
    public void reset(){
        tb_namaKelompok.setText("");
        tb_searchKelompok.setText("");
    }
    public Object getB_search(){
        return b_searchKelompok;
    }
    
    public Object getB_Exit(){
        return EXIT;
    }
    
     public JTable getTable(){
        return t_Kelompok;
    }
     public void resettabel() {
        for (int j = 0; j < 40; j++) {
            t_Kelompok.setValueAt(null, j, 0);
            t_Kelompok.setValueAt(null, j, 1);
        }
    }
    public void addListener(ActionListener e){
        b_InsertKelompok.addActionListener(e);
        b_deleteKelompok.addActionListener(e);
        b_searchKelompok.addActionListener(e);
        D_Menu_Lokasi.addActionListener(e);
        D_Menu_Kelompok.addActionListener(e);        
        D_Menu_Pembimbing.addActionListener(e);
        D_Menu_Mahasiswa.addActionListener(e);
        c_pilihLokasi.addActionListener(e);
        EXIT.addActionListener(e);
    }
    
}
