/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Reza22
 */
public class awal extends javax.swing.JFrame {

    /**
     * Creates new form awal
     */
    public awal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tb_namaLokasi = new javax.swing.JTextField();
        b_searchLokasi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tb_searchLokasi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_Lokasi = new javax.swing.JTable();
        b_InsertLokasi = new javax.swing.JButton();
        b_deleteLokasi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        D_Menu = new javax.swing.JMenu();
        D_Menu_Lokasi = new javax.swing.JMenuItem();
        D_Menu_Kelompok = new javax.swing.JMenuItem();
        D_Menu_Pembimbing = new javax.swing.JMenuItem();
        D_Menu_Mahasiswa = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenu();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAMA LOKASI");

        b_searchLokasi.setText("SEARCH");

        jLabel2.setText("SEARCH");

        t_Lokasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Lokasi", "Pembimbing", "Jumlah Kelompok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        t_Lokasi.setEditingColumn(0);
        t_Lokasi.setEditingRow(0);
        t_Lokasi.setEnabled(false);
        jScrollPane1.setViewportView(t_Lokasi);

        b_InsertLokasi.setText("INSERT");

        b_deleteLokasi.setText("DELETE");

        D_Menu.setText("MENU");

        D_Menu_Lokasi.setText("LOKASI");
        D_Menu.add(D_Menu_Lokasi);

        D_Menu_Kelompok.setText("KELOMPOK");
        D_Menu.add(D_Menu_Kelompok);

        D_Menu_Pembimbing.setText("PEMBIMBING");
        D_Menu.add(D_Menu_Pembimbing);

        D_Menu_Mahasiswa.setText("MAHASISWA");
        D_Menu.add(D_Menu_Mahasiswa);

        jMenuBar1.add(D_Menu);

        Exit.setText("EXIT");
        jMenuBar1.add(Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tb_searchLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_searchLokasi)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_InsertLokasi)
                                .addGap(18, 18, 18)
                                .addComponent(b_deleteLokasi)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tb_namaLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tb_namaLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_InsertLokasi)
                    .addComponent(b_deleteLokasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_searchLokasi)
                    .addComponent(jLabel2)
                    .addComponent(tb_searchLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu D_Menu;
    private javax.swing.JMenuItem D_Menu_Kelompok;
    private javax.swing.JMenuItem D_Menu_Lokasi;
    private javax.swing.JMenuItem D_Menu_Mahasiswa;
    private javax.swing.JMenuItem D_Menu_Pembimbing;
    private javax.swing.JMenu Exit;
    private javax.swing.JButton b_InsertLokasi;
    private javax.swing.JButton b_deleteLokasi;
    private javax.swing.JButton b_searchLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_Lokasi;
    private javax.swing.JTextField tb_namaLokasi;
    private javax.swing.JTextField tb_searchLokasi;
    // End of variables declaration//GEN-END:variables

    public String getNamaLokasi() {
        return tb_namaLokasi.getText();
    }

    public String getSearchLokasi() {
        return tb_searchLokasi.getText();
    }

    public Object getB_Add() {
        return b_InsertLokasi;
    }
    public void gagal(){
        JOptionPane.showMessageDialog(null, "Isi terlebih dahulu");
    }
    public void sukses(){
        JOptionPane.showMessageDialog(null, "Berhasil");
    }

    public Object getB_Delete() {
        return b_deleteLokasi;
    }

    public Object getB_search() {
        return b_searchLokasi;
    }

    public Object getB_Exit() {
        return Exit;
    }

    public Object getD_Menu_Lokasi() {
        return D_Menu_Lokasi;
    }

    public Object getD_Menu_Kelompok() {
        return D_Menu_Kelompok;
    }

    public Object getD_Menu_Pembimbing() {
        return D_Menu_Pembimbing;
    }

    public Object getD_Menu_Mahasiswa() {
        return D_Menu_Mahasiswa;
    }

    public JTable getTable() {
        return t_Lokasi;
    }

//    public int selectedTableint{
//        
//        return ;
//}
    public void resettabel() {
        for (int j = 0; j < 40; j++) {
            t_Lokasi.setValueAt(null, j, 0);
            t_Lokasi.setValueAt(null, j, 1);
            t_Lokasi.setValueAt(null, j, 2);
        }
    }

    
    public void reset() {
        tb_namaLokasi.setText("");
        tb_searchLokasi.setText("");
    }

    public Object getB_searchLokasi() {
        return b_searchLokasi;
    }

    public Object getExit() {
        return Exit;
    }

    public JTable gett_lokasi() {
        return t_Lokasi;
    }

    public void addListener(ActionListener e) {
        b_InsertLokasi.addActionListener(e);
        b_deleteLokasi.addActionListener(e);
        b_searchLokasi.addActionListener(e);
        D_Menu_Lokasi.addActionListener(e);
        D_Menu_Kelompok.addActionListener(e);
        D_Menu_Pembimbing.addActionListener(e);
        D_Menu_Mahasiswa.addActionListener(e);
        Exit.addActionListener(e);
    }
}
