/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author Reza22
 */
public class awal_mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form awal_mahasiswa
     */
    public awal_mahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_deleteMahasiswa = new javax.swing.JButton();
        b_InsertMahasiswa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_Mahasiswa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tb_searchMahasiswa = new javax.swing.JTextField();
        b_searchMahasiswa = new javax.swing.JButton();
        c_pilihLokasi = new javax.swing.JComboBox<>();
        c_pilihKelompok = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tb_namaMahasiswa = new javax.swing.JTextField();
        tb_nimMahasiswa = new javax.swing.JTextField();
        tb_kelasMahasiswa = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        D_Menu = new javax.swing.JMenu();
        D_Menu_Lokasi = new javax.swing.JMenuItem();
        D_Menu_Kelompok = new javax.swing.JMenuItem();
        D_Menu_Pembimbing = new javax.swing.JMenuItem();
        D_Menu_Mahasiswa = new javax.swing.JMenuItem();
        EXIT = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_deleteMahasiswa.setText("DELETE");

        b_InsertMahasiswa.setText("INSERT");

        t_Mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Mahasiswa", "NIM", "Kelas", "Kelompok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t_Mahasiswa);

        jLabel2.setText("SEARCH");

        b_searchMahasiswa.setText("SEARCH");

        c_pilihLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_pilihLokasiActionPerformed(evt);
            }
        });

        jLabel1.setText("NAMA MAHASISWA");

        jLabel3.setText("NIM MAHASISWA");

        jLabel4.setText("KELAS MAHASISWA");

        D_Menu.setText("MENU");

        D_Menu_Lokasi.setText("LOKASI");
        D_Menu.add(D_Menu_Lokasi);

        D_Menu_Kelompok.setText("KELOMPOK");
        D_Menu.add(D_Menu_Kelompok);

        D_Menu_Pembimbing.setText("PEMBIMBING");
        D_Menu.add(D_Menu_Pembimbing);

        D_Menu_Mahasiswa.setText("MAHASISWA");
        D_Menu.add(D_Menu_Mahasiswa);

        jMenuBar1.add(D_Menu);

        EXIT.setText("EXIT");
        jMenuBar1.add(EXIT);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_searchMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_searchMahasiswa)
                                .addGap(129, 129, 129))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(b_InsertMahasiswa)
                                .addGap(18, 18, 18)
                                .addComponent(b_deleteMahasiswa)
                                .addGap(448, 448, 448)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c_pilihKelompok, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                            .addComponent(c_pilihLokasi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_namaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_nimMahasiswa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_kelasMahasiswa)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_pilihLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tb_namaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_pilihKelompok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tb_nimMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_kelasMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_InsertMahasiswa)
                    .addComponent(b_deleteMahasiswa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_searchMahasiswa)
                    .addComponent(jLabel2)
                    .addComponent(tb_searchMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_pilihLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_pilihLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_pilihLokasiActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu D_Menu;
    private javax.swing.JMenuItem D_Menu_Kelompok;
    private javax.swing.JMenuItem D_Menu_Lokasi;
    private javax.swing.JMenuItem D_Menu_Mahasiswa;
    private javax.swing.JMenuItem D_Menu_Pembimbing;
    private javax.swing.JMenu EXIT;
    private javax.swing.JButton b_InsertMahasiswa;
    private javax.swing.JButton b_deleteMahasiswa;
    private javax.swing.JButton b_searchMahasiswa;
    private javax.swing.JComboBox<String> c_pilihKelompok;
    private javax.swing.JComboBox<String> c_pilihLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_Mahasiswa;
    private javax.swing.JTextField tb_kelasMahasiswa;
    private javax.swing.JTextField tb_namaMahasiswa;
    private javax.swing.JTextField tb_nimMahasiswa;
    private javax.swing.JTextField tb_searchMahasiswa;
    // End of variables declaration//GEN-END:variables

    public JComboBox getComboBoxLokasi(){
        return c_pilihLokasi;
    }
    public JComboBox getComboBoxKelompok(){
        return c_pilihKelompok;
    }
    public int getPilihLokasi(){
        return c_pilihLokasi.getSelectedIndex();
    }
    public int getPilihKelompok(){
        return c_pilihKelompok.getSelectedIndex();
    }
    public String getNamaMahasiswa(){
        return tb_namaMahasiswa.getText();
    }
    public String getNimMahasiswa(){
        return tb_nimMahasiswa.getText();
    }
    public String getKelasMahasiswa(){
        return tb_kelasMahasiswa.getText();
    }
    public String getSearchMahasiswa(){
        return tb_searchMahasiswa.getText();
    }
    
    public void addComboBoxLokasi(String[] nama){
        c_pilihLokasi.setModel(new DefaultComboBoxModel<>(nama));
    }
    
    public void addComboBoxKelompok(String[] nama){
        c_pilihKelompok.setModel(new DefaultComboBoxModel<>(nama));
    }
    
    public void resettabel() {
        for (int j = 0; j < 40; j++) {
            t_Mahasiswa.setValueAt(null, j, 0);
            t_Mahasiswa.setValueAt(null, j, 1);
        }
    }
    
    public Object getB_Add(){
        return b_InsertMahasiswa;
    }
    
    public Object getB_Delete(){
        return b_deleteMahasiswa;
    }
    public Object getD_Menu_Lokasi(){
        return D_Menu_Lokasi;
    }
    
    public Object getD_Menu_Kelompok(){
        return D_Menu_Kelompok;
    }
    
    public Object getD_Menu_Pembimbing(){
        return D_Menu_Pembimbing;
    }
    
    public Object getD_Menu_Mahasiswa(){
        return D_Menu_Mahasiswa;
    }
    public void reset(){
        tb_namaMahasiswa.setText("");
        tb_nimMahasiswa.setText("");
        tb_kelasMahasiswa.setText("");
        tb_searchMahasiswa.setText("");
    }
    
    public Object getB_search(){
        return b_searchMahasiswa;
    }
    
    public Object getB_Exit(){
        return EXIT;
    }
     public JTable getTable(){
        return t_Mahasiswa;
    }
    
    public void addListener(ActionListener e){
        b_InsertMahasiswa.addActionListener(e);
        b_deleteMahasiswa.addActionListener(e);
        b_searchMahasiswa.addActionListener(e);
        D_Menu_Lokasi.addActionListener(e);
        D_Menu_Kelompok.addActionListener(e);        
        D_Menu_Pembimbing.addActionListener(e);
        D_Menu_Mahasiswa.addActionListener(e);
        EXIT.addActionListener(e);
    }
}
